### ISSUE TITLE
Is there a corresponding paper for this code?

### ISSUE THREAD

**Issue by 1219-wangjindong** [saugat76/UAV_Subband_Allocation_DQN_Pytorch#7]
Hi Dr., is there a corresponding paper for this code? If there is can you tell me, thanks a lot. Have a nice life!

**Comment by saugat76** [comment]
Hello. Thank you for reaching out. The article following this code is currently awaiting acceptance and the preprint should be available is few weeks. I would link it on this feed once it is available.

**Comment by 1219-wangjindong** [comment]
It is a great honor to have you reply. I would like to ask, is this code based on cellular network for UAV-assisted communication? It is the one that uses the drone as a base station for user association and power distribution. Is it such a scenario?

**Comment by saugat76** [comment]
Currently the code is working to maximize the user connectivity without any additional consideration. All the scenarios used in the simulation assumes UAV working as a base station communicating to core network through a backhaul link. So, we only focus on UAV to user communication, and UAV are not working as a cellular system not are connected to a cellular network and work as a independent wireless communication system.

**Comment by saugat76** [comment]
Hello, here is the link to the complete report you are looking for https://rave.ohiolink.edu/etdc/view?acc_num=miami1688867280874635. The project is a part of a thesis. If you have any queries or suggestions please feel free  to reach out.
