### ISSUE TITLE
Is there a corresponding paper for this code?

### ISSUE THREAD

**Issue by 670555467** [saugat76/UAV_Subband_Allocation_DQN_Pytorch#8]

**Comment by saugat76** [comment]
Sorry for late response. I am waiting approval of publication of my thesis. It should be available in few days. Afterward I will provide a link to it in this issue.

**Comment by saugat76** [comment]
Hello, here is the link to the complete report you are looking for https://rave.ohiolink.edu/etdc/view?acc_num=miami1688867280874635. The project is a part of a thesis. If you have any queries or suggestions please feel free  to reach out.
